import 'dart:io';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PrescriptionPdfService {
  // ── Build the PDF document from the prescription markdown ──────────────
  Future<pw.Document> buildPdf({
    required String prescriptionMarkdown,
    required String patientName,
    required String doctorName,
    required String clinicName,
    required String clinicalNotes, // original transcript for reference
  }) async {
    final pdf = pw.Document();
    final dateStr = DateFormat('dd MMM yyyy').format(DateTime.now());
    final timeStr = DateFormat('HH:mm').format(DateTime.now());

    // ── Parse markdown into sections ─────────────────────────────────────
    final sections = _parseSections(prescriptionMarkdown);

    // ── Define styles ────────────────────────────────────────────────────
    final baseFont = pw.Font.helvetica();
    final boldFont = pw.Font.helveticaBold();

    final titleStyle = pw.TextStyle(
      font: boldFont,
      fontSize: 20,
      color: PdfColors.teal800,
    );
    final headingStyle = pw.TextStyle(
      font: boldFont,
      fontSize: 13,
      color: PdfColors.teal700,
    );
    final bodyStyle = pw.TextStyle(font: baseFont, fontSize: 11);
    final mutedStyle = pw.TextStyle(
      font: baseFont,
      fontSize: 10,
      color: PdfColors.grey600,
    );
    final smallBoldStyle = pw.TextStyle(font: boldFont, fontSize: 10);

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (ctx) => _buildHeader(
          doctorName: doctorName,
          clinicName: clinicName,
          dateStr: dateStr,
          timeStr: timeStr,
          titleStyle: titleStyle,
          mutedStyle: mutedStyle,
          smallBoldStyle: smallBoldStyle,
        ),
        footer: (ctx) => _buildFooter(ctx, mutedStyle),
        build: (ctx) => [
          // Patient info banner
          _patientBanner(patientName, dateStr, bodyStyle, smallBoldStyle),
          pw.SizedBox(height: 16),

          // Render each section from the parsed markdown
          for (final entry in sections.entries) ...[
            pw.Text(entry.key, style: headingStyle),
            pw.Divider(color: PdfColors.teal100, thickness: 0.8),
            pw.SizedBox(height: 4),
            _renderSectionContent(entry.value, bodyStyle, boldFont, baseFont),
            pw.SizedBox(height: 14),
          ],

          // Original clinical notes (collapsed / reference section)
          pw.SizedBox(height: 8),
          pw.Text('Original Clinical Notes (Dictation)',
              style: headingStyle.copyWith(color: PdfColors.grey600)),
          pw.Divider(color: PdfColors.grey300),
          pw.Text(clinicalNotes, style: mutedStyle),

          // Signature line
          pw.SizedBox(height: 32),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Container(width: 160, height: 1, color: PdfColors.grey700),
                    pw.SizedBox(height: 4),
                    pw.Text(
                        doctorName.isNotEmpty ? doctorName : 'Doctor\'s Signature',
                        style: smallBoldStyle),
                  ]),
              pw.Text('Date: $dateStr', style: bodyStyle),
            ],
          ),
        ],
      ),
    );

    return pdf;
  }

  // ── Header widget ──────────────────────────────────────────────────────
  pw.Widget _buildHeader({
    required String doctorName,
    required String clinicName,
    required String dateStr,
    required String timeStr,
    required pw.TextStyle titleStyle,
    required pw.TextStyle mutedStyle,
    required pw.TextStyle smallBoldStyle,
  }) {
    return pw.Column(children: [
      pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
            pw.Text(
              clinicName.isNotEmpty ? clinicName : 'Medical Prescription',
              style: titleStyle,
            ),
            if (doctorName.isNotEmpty)
              pw.Text('Dr. $doctorName', style: smallBoldStyle),
          ]),
          pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.end, children: [
            pw.Text('Date: $dateStr', style: mutedStyle),
            pw.Text('Time: $timeStr', style: mutedStyle),
            pw.Text('Generated by MedGemma AI', style: mutedStyle),
          ]),
        ],
      ),
      pw.Divider(color: PdfColors.teal700, thickness: 1.5),
      pw.SizedBox(height: 8),
    ]);
  }

  // ── Footer widget ──────────────────────────────────────────────────────
  pw.Widget _buildFooter(pw.Context ctx, pw.TextStyle mutedStyle) {
    return pw.Column(children: [
      pw.Divider(color: PdfColors.grey300),
      pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'CONFIDENTIAL — This prescription was AI-assisted. '
            'Verify all information before dispensing.',
            style: mutedStyle.copyWith(color: PdfColors.red700),
          ),
          pw.Text('Page ${ctx.pageNumber}/${ctx.pagesCount}', style: mutedStyle),
        ],
      ),
    ]);
  }

  // ── Patient banner ─────────────────────────────────────────────────────
  pw.Widget _patientBanner(
    String name,
    String date,
    pw.TextStyle body,
    pw.TextStyle bold,
  ) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        color: PdfColors.teal50,
        border: pw.Border.all(color: PdfColors.teal200),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(6)),
      ),
      child: pw.Row(children: [
        pw.Text('Patient: ', style: bold),
        pw.Text(name.isNotEmpty ? name : '___________________', style: body),
        pw.Spacer(),
        pw.Text('Date: $date', style: body),
      ]),
    );
  }

  // ── Section content renderer ───────────────────────────────────────────
  pw.Widget _renderSectionContent(
    String content,
    pw.TextStyle body,
    pw.Font boldFont,
    pw.Font baseFont,
  ) {
    // Detect markdown table (lines containing '|')
    final lines = content.trim().split('\n');
    final hasTable = lines.any((l) => l.trim().startsWith('|'));

    if (hasTable) {
      return _renderTable(lines, body, boldFont, baseFont);
    }

    // Render as bullet list if lines start with '-' or '*'
    final isList = lines.every((l) =>
        l.trim().startsWith('-') ||
        l.trim().startsWith('*') ||
        l.trim().isEmpty);

    if (isList) {
      return pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: lines
            .where((l) => l.trim().isNotEmpty)
            .map((l) => pw.Row(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('• ', style: body),
                    pw.Expanded(
                      child: pw.Text(
                        l.replaceFirst(RegExp(r'^[-*]\s*'), '').trim(),
                        style: body,
                      ),
                    ),
                  ],
                ))
            .toList(),
      );
    }

    // Default: plain paragraph
    return pw.Text(content.trim(), style: body);
  }

  // ── Markdown table → PDF table ─────────────────────────────────────────
  pw.Widget _renderTable(
    List<String> lines,
    pw.TextStyle body,
    pw.Font boldFont,
    pw.Font baseFont,
  ) {
    final tableLines = lines
        .where((l) => l.trim().startsWith('|') && !l.trim().startsWith('|---'))
        .toList();

    if (tableLines.isEmpty) return pw.SizedBox();

    final rows = tableLines.map((line) {
      return line
          .split('|')
          .map((c) => c.trim())
          .where((c) => c.isNotEmpty)
          .toList();
    }).toList();

    final headers = rows.first;
    final dataRows = rows.skip(1).toList();

    return pw.TableHelper.fromTextArray(
      headers: headers,
      data: dataRows,
      headerStyle: pw.TextStyle(font: boldFont, fontSize: 10),
      cellStyle: pw.TextStyle(font: baseFont, fontSize: 10),
      headerDecoration: const pw.BoxDecoration(color: PdfColors.teal50),
      border: pw.TableBorder.all(color: PdfColors.grey300),
      cellPadding: const pw.EdgeInsets.all(5),
    );
  }

  // ── Parse markdown ## sections into a LinkedHashMap ───────────────────
  Map<String, String> _parseSections(String markdown) {
    final result = <String, String>{};
    final lines = markdown.split('\n');
    String? currentSection;
    final buffer = StringBuffer();

    for (final line in lines) {
      if (line.startsWith('## ')) {
        if (currentSection != null) {
          result[currentSection] = buffer.toString().trim();
          buffer.clear();
        }
        currentSection = line.replaceFirst('## ', '').trim();
      } else if (line.startsWith('# ')) {
        // Top-level title — skip
        continue;
      } else if (currentSection != null) {
        buffer.writeln(line);
      }
    }
    if (currentSection != null) {
      result[currentSection] = buffer.toString().trim();
    }
    return result;
  }

  // ── Save to disk & return path ─────────────────────────────────────────
  Future<String> savePdf(pw.Document pdf, String patientName) async {
    final dir = await getApplicationDocumentsDirectory();
    final prescriptionsDir = Directory('${dir.path}/prescriptions');
    if (!prescriptionsDir.existsSync()) prescriptionsDir.createSync();

    final timestamp = DateFormat('yyyyMMdd_HHmm').format(DateTime.now());
    final safeName = patientName.trim().isEmpty
        ? 'patient'
        : patientName.trim().replaceAll(RegExp(r'[^\w]'), '_');
    final filename = 'rx_${safeName}_$timestamp.pdf';
    final file = File('${prescriptionsDir.path}/$filename');

    await file.writeAsBytes(await pdf.save());
    return file.path;
  }

  // ── Preview/share via printing package ────────────────────────────────
  Future<void> previewAndShare(pw.Document pdf) async {
    await Printing.layoutPdf(
      onLayout: (format) async => pdf.save(),
      name: 'MedGemma Prescription',
    );
  }
}
